
title: Poesía Medieval
description: Reconstrucción y contrafactum en la poesía ibérica medieval.
baseurl: "/mini-MF" # the subpath of your site, e.g. /blog
url: "http://github.com/AgustinaRyckeboer/" # the base hostname & protocol for your site
github_repo: mini-MF # the GitHub repo name for your project
github_username: hdcaicyt

social_link: twitter
social_username: hdcaicyt

theme_color: light

# Build settings
markdown: kramdown

collections:
    cantigas:
      output: true
    preguntas_respuestas:
      output: true